@startuml activity0

title UML Activity Diagram - Physical Asset Trading Platform

|Owner|
start
:Tokenize Physical Asset into NFT;
|Blockchain|
:Store Physical NFT Asset Data;
|Owner|
if () then ([sell])
  :List Physical NFT Asset;
else ([other])
  end
endif
|Buyer|
:Purchase Physical NFT Asset;
|Owner|
:Deliver Physical Asset;
|Buyer|
if () then ([success])
  #palegreen:Verification Successful - Confirm Delivery;
else ([failure])
  #pink:Verification Failed;
  end
endif
stop
@enduml
