enum ItemState {
  NewEscrow
  NftDeposited
  CancelNft
  EthDeposited
  CanceledBeforeDelivery
  DeliveryInitiated
  Delivered
}

interface IERC721 {
  transferFrom(from, to, tokenId)
}

class beeTokenEscrow {
  - feeAccount: payable address
  - feePercent: uint
  - itemCount: uint
  - seller: payable address
  - buyer: payable address
  - items: mapping(uint => Item)

  + listNFT(_nft: IERC721, _tokenId: uint256, _price: uint)
  + setItemStateByTokenId(tokenId: uint256, newState: ItemState)
  + reverseNftTransfer(_tokenId: uint)
  + cancelBeforeDelivery(_tokenId: uint)
  + depositETH(_tokenId: uint) payable
  + initiateDelivery(_tokenId: uint)
  + confirmDeliveryFinalizeSale(_tokenId: uint)
  + getTotalPrice(_tokenId: uint) view returns (uint)
}

class Item {
  - itemId: uint
  - tokenId: uint256
  - nft: IERC721
  - price: uint
  - seller: payable address
  - sold: bool
  - state: ItemState
}

beeTokenEscrow --> Item
Item --> IERC721
