@startuml usecase2
left to right direction
skinparam packageStyle rectangle

actor Owner as "Owner/Seller"
actor Buyer as "Buyer"

rectangle "Blockchain" as Blockchain
rectangle "NFT smart contract" as NFTContract
rectangle "Escrow smart contract" as EscrowContract

rectangle "Physical Asset Trading System" {
  rectangle "UC1: Tokenization\nof physical asset" as Tokenization
  rectangle "UC2: Listing physical\nNFT asset" as Listing
  rectangle "UC3: Purchase of\nphysical NFT asset" as Purchase
  rectangle "UC4: Deliver physical asset" as Delivery
  rectangle "UC5: Receive physical asset" as Receive
  rectangle "UC6: Verify physical asset" as Verification
  rectangle "UC7: Receive physical NFT ownership " as NFTOwnership
  rectangle "UC8: Receive ETHs" as ETH

  Owner --> Tokenization
  Tokenization --> NFTContract : Mint physical NFT

  NFTContract --> Blockchain : Store data on blockchain

  Owner --> Listing
  Listing --> EscrowContract : Transfer physical NFT

  Buyer --> Purchase
  Purchase --> EscrowContract : Transfer ETH

  Owner --> Delivery

  Buyer --> Receive

  Buyer --> Verification

  Verification --> EscrowContract : Confirm delivery

  Buyer --> NFTOwnership
  
  EscrowContract --> NFTOwnership : Transfer ownership

  Owner --> ETH

  EscrowContract --> ETH : Transfer ETH 

  NFTContract --|> Blockchain

  EscrowContract --|> Blockchain
}

@enduml


