@startuml usecase1
left to right direction
skinparam packageStyle rect
actor "Physical Asset Owners" as Owners
actor Buyers
rectangle "Physical Asset Trading Platform" {
  usecase "Access DApp" as UC1
  usecase "Tokenize Physical Asset" as UC2
  usecase "Track Physical Asset on Blockchain" as UC3
  usecase "Authenticate Physical Asset" as UC4
  usecase "Sell Tokenized Physical Asset" as UC5
  usecase "Purchase Tokenized Physical Asset" as UC6
}
Owners --> UC1
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
UC4 --> UC5
Buyers --> UC6
@enduml
