@startuml usecase0
left to right direction
skinparam packageStyle rect
actor Owner
actor Buyer
rectangle Platform {
  usecase "Tokenize physical asset into NFT" as UC1
  usecase "List physical NFT for sale" as UC2
  usecase "Buy physical NFT" as UC3
  usecase "Deliver physical asset" as UC4
  usecase "Confirm delivery of physical asset" as UC5
}
rectangle Blockcahin {}

Owner --> UC1
Owner --> UC2
Buyer --> UC3
Owner --> UC4
Buyer --> UC5
@enduml

