@startuml class2

title UML Class Diagram - NFT Contract

interface ERC721URIStorage {
    + _setTokenURI(tokenId: uint256, tokenURI: string): void
    + _burn(tokenId: uint256): void
    + tokenURI(tokenId: uint256): string
}

interface Ownable {
    + owner(): address
    + onlyOwner(): modifier
}

class beeToken {
    + tokenCount: uint
    + beeToken()
    + mint(_tokenURI: string): uint
    + withdraw(): void
}

ERC721URIStorage <|.. beeToken
Ownable <|.. beeToken

@enduml

